// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// Author comment: This file should be generated by flutterfire don't edit manually for God's sake!!!

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PUT YOUR API KEY HERE',
    appId: 'PUT YOUR API KEY HERE',
    messagingSenderId: 'PUT YOUR API KEY HERE',
    projectId: 'put your project id here',
    storageBucket: 'storage',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PUT YOUR API KEY HERE',
    appId: 'PUT YOUR API KEY HERE',
    messagingSenderId: 'PUT YOUR API KEY HERE',
    projectId: 'put your project id here',
    storageBucket: 'storage',
    iosBundleId: 'com.isakajames.notification',
  );
}
